
# docker-compose.yml
version: '3.8'
services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./services/user-service:/app

  product-service:
    build: ./services/product-service
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./services/product-service:/app

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "8000:5000"
    environment:
      - USER_SERVICE_URL=http://user-service:5000
      - PRODUCT_SERVICE_URL=http://product-service:5000
      - FLASK_ENV=development
    depends_on:
      - user-service
      - product-service
    volumes:
      - ./services/gateway-service:/app