# helm/nubus-demo/values-dev.yaml
# Development values for nubus-demo chart

replicaCount: 1

image:
  repository: ""  # Leave empty for local images
  tag: latest
  pullPolicy: IfNotPresent  # Important for local images

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: nubus-demo-dev.local
      paths:
        - path: /
          pathType: Prefix

environment: dev

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi